storage_options = None
storage_names = None
package_names = None
price_list = "Прайс лист отсутствует"
support_contacts = "Для технической поддержки пишите разработчику в ЛС (@EgorRy)"
operator = 1202939724
package_options = None
database_path = "MAIN.sql"
database_user_name = "root"
database_user_password = "root"
force_new_database = False
delay = 3
admins = [1202939724]